### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by MakisH** [solids4foam/solids4foam-tutorials-benchmark-data#2]
This repository only contains results, but no configuration files or `README.md` explaining the differences in the settings. Since this is a separate repository, metadata such as solids4foam version etc would also be useful.

In case all the configuration is supposed to be exactly as in the tutorials, more links and `README.md` files would help understand what results are generated how.

This might sound like a lot of work, but you could already achieve a lot just with adding more information in the central `README.md`.

This is in the context of my review for the JOSS publication (https://github.com/openjournals/joss-reviews/issues/7407).

**Comment by philipcardiff** [comment]
A central `README.md` has been added. Adding individual `README.md` files is something we can consider as we add more data. For now, I think we can close this point. But feel free to re-open it!
